### ISSUE TITLE
JSON.pm include error when running ./admin/replication/LoadReplicationChanges

### ISSUE THREAD

**Issue by gregsochanik** [metabrainz/musicbrainz-docker#41]
I'm trying to update the db to schema 24 and I'm getting the following error when running both ./admin/replication/LoadReplicationChanges and ./update.sh from within the `musicbrainz_docker_musicbrainz_1` container:

```
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /musicbrainz-server/admin/replication/../../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /musicbrainz-server/admin/replication/../../lib/DBDefs/Default.pm line 32.
BEGIN failed--compilation aborted at /musicbrainz-server/admin/replication/../../lib/DBDefs/Default.pm line 32.
Compilation failed in require at /usr/share/perl/5.22/parent.pm line 20.
BEGIN failed--compilation aborted at /musicbrainz-server/admin/replication/../../lib/DBDefs.pm line 29.
Compilation failed in require at ./admin/replication/LoadReplicationChanges line 32.
BEGIN failed--compilation aborted at ./admin/replication/LoadReplicationChanges line 32.

```
./upgrade.sh
```
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at lib/DBDefs/Default.pm line 32.
BEGIN failed--compilation aborted at lib/DBDefs/Default.pm line 32.
Compilation failed in require at /usr/share/perl/5.22/parent.pm line 20.
BEGIN failed--compilation aborted at lib/DBDefs.pm line 29.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

```

Is there a step missing in the setup, or does something need to be added to the PATH env var?

Thanks,
Greg

**Comment by gregsochanik** [comment]
In addition I ran the following (taken from the musicbrainz-server INSTALL.md [here](https://github.com/metabrainz/musicbrainz-server/blob/master/INSTALL.md#installing-perl-dependencies)):

`docker exec musicbrainzdocker_musicbrainz_1 cpanm --installdeps --notest .`

which installs all the missing deps and fixes the issue, but a rebuild of the `musicbrainz` container (via `docker-compose build`) will cause the deps to be missing again. 

Should the above command be run as part of the Dockerfile? If so I could submit a PR with it added if you like.

Have you experienced this issue?

**Comment by gregsochanik** [comment]
Ahhh - it's already _in_ the Dockerfile here: 

https://github.com/jsturgis/musicbrainz-docker/blob/master/musicbrainz-dockerfile/Dockerfile#L27

**Comment by andrewalba** [comment]
@gregsochanik ,

Ran into similar issue and I am just guessing here, but I believe it is because of how the additional cpan packages are being installed. You can try changing https://github.com/jsturgis/musicbrainz-docker/blob/master/musicbrainz-dockerfile/Dockerfile#L28 to the following
`RUN eval $( perl -Mlocal::lib) && cpanm --notest Plack::Middleware::Debug::Base \`
This should put the modules in the right directory.

**Comment by gregsochanik** [comment]
@andrewalba thanks, will give it a go.

**Comment by pdf** [comment]
I'm not sure the explicit perl lib installations in the Dockerfile are required at all any more, but to run any of the MusicBrainz scripts from a shell inside the container (for recent MB versions), you'll need to get the `local::lib` environment vars set by executing the following inside the shell:

```bash
eval $( perl -Mlocal::lib)
```

The MB docs recommend adding this to your .bashrc or whatever, but I haven't investigated how best to approach this with docker, so I just execute it manually.

**Comment by jsturgis** [comment]
@pdf thanks for the help with this issue, I am looking into it along with some other issues that came up after the last schema update release. Hopefully I will have this fixed soon, but if you fix it first submit a PR here and I'll merge it, thanks.

**Comment by pdf** [comment]
@jsturgis with #45 merged (primarily for the DBD-Pg downgrade), I have a fully functional system (without e2e46c23f35d318c80b568e337e99800783aaad5 or a346a921349eb58592e298f1a2bd54c88cf979d3).

This particular issue is mostly a documentation problem, since the upgrade instructions don't take into account upstream changes.  I'll take a pass over the README later today, and maybe just provide an `upgrade.sh` wrapper that performs a replication update, then calls the `musicbrainz-server/upgrade.sh` script.

**Comment by pdf** [comment]
@jsturgis I've now tested after applying #45 and #47 to the latest changes on master, and everything looks good, thanks for your efforts.

**Comment by jsturgis** [comment]
Fixed by #45 and #47

**Comment by pdf** [comment]
This issue still needs some documentation fixes, and maybe a new wrapper, before it's resolved.
